### OBTENER TODAS LAS CARTAS DE LA BASE DE DATOS
GET http://localhost:3000/api/cards

### CREAR UN NUEVO JUGADOR
POST http://localhost:3000/api/jugador/registro
Content-Type: application/json

{
    "nombre" : "zumaya90",
    "clave" : "zum1234"
}

### INICIAR UNA PARTIDA CON DOS JUGADORES
POST http://localhost:3000/api/partida
Content-Type: application/json

{
    "jugadorRojo" : "JugadorAvanzado",
    "jugadorAzul" : "JugadorNovato"
}

### REGISTRAR EL GANADOR DE UNA PARTIDA
POST http://localhost:3000/api/partida/ganador
Content-Type: application/json

{
    "id_partida" : 7,
    "id_jugador_ganador" : 5
}

###OBTENER A UN JUGADOR POR USERNAME Y PASSWORD (LOGIN)
GET http://localhost:3000/api/jugador/inicio_sesion/zumaya90/zum1234

### OBTENER TODOS LOS JUGADORES
GET http://localhost:3000/api/jugadores